#
# Defines environment variables.
#
# Authors: Dan Riley <hello@danriley.me>
# License: beerware.
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export NODE_PATH=$NODE_PATH:`npm root -g`